global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'http_server'
    static_configs:
      - targets: ['http_server:9100']
  - job_name: 'tcp_server'
    static_configs:
      - targets: ['tcp_server:9101']
  - job_name: 'udp_server'
    static_configs:
      - targets: ['udp_server:9102']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']